dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9-dev"
script: tox
after_success:
  - coveralls

notifications:
  email:
    on_failure: change
env:
    global:
      - TEST_PYPI_URL=https://test.pypi.org/legacy/
      - PYPI_URL=https://upload.pypi.org/legacy/
install:
  - pip install --upgrade pip && pip install -r requirements.txt && pip install --upgrade -r dev-requirements.txt && pip install .
cache: pip

stages:
  - test
  - "Local Installation Test"
  - "Coverage"
  - "Build docs"
  - "Deploy to PyPI"
  - "PyPI Installation Test"

jobs:
  include:
    - &local_installation_test
      stage: "Local Installation Test"
      python: "3.7"
      script: bash tests/local_installation_test.sh
    - <<: *local_installation_test
      python: "3.8"
    - <<: *local_installation_test
      python: "3.9-dev"

    - &coverage
      stage: "Coverage"
      python: "3.7"
      script: coverage run --rcfile=.coveragerc setup.py test -s tests.unit
    - <<: *coverage
      python: "3.8"
    - <<: *coverage
      python: "3.9-dev"

    - stage: "Build docs"
      script: cd sphinx && make clean && make html

    - &deploy_to_pypi
      stage: "Deploy to PyPI"
      python: "3.7"
      script: bash deploy/deploy_to_pypi.sh
    - <<: *deploy_to_pypi
      python: "3.8"
    - <<: *deploy_to_pypi
      python: "3.9-dev"

    - &pypi_installation_test
      stage: "PyPI Installation Test"
      python: "3.7"
      if: branch = master
      script: bash tests/pypi_installation_test.sh
    - <<: *pypi_installation_test
      python: "3.8"
    - <<: *pypi_installation_test
      python: "3.9-dev"
